CREATE DATABASE SENAI_HROADS_TARDE

USE SENAI_HROADS_TARDE;

CREATE TABLE TIPO_HABILIDADE(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(250) NOT NULL UNIQUE
)

CREATE TABLE HABILIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE 
	,ID_TIPO_HABILIDADE INT FOREIGN KEY REFERENCES TIPO_HABILIDADE(ID)
)

CREATE TABLE CLASSES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
)

CREATE TABLE PERSONAGENS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL UNIQUE
	,CAPACIDADE_MAXIMA_VIDA INT NOT NULL
	,CAPACIDADE_MAXIMA_MANA INT NOT NULL
	,DATA_DE_ATUALIZACAO DATETIME NOT NULL
	,DATA_DE_CRIACAO DATETIME NOT NULL
)


CREATE TABLE CLASSE_HABILIDADE(
	ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID) NOT NULL
	,ID_HABILIDADE INT FOREIGN KEY REFERENCES HABILIDADES(ID)
)

ALTER TABLE PERSONAGENS
ADD ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID)