use SENAI_HROADS_TARDE;

INSERT INTO TIPO_HABILIDADE(NOME)
VALUES ('Ataque'), ('Defesa'), ('Magia')

INSERT INTO TIPO_HABILIDADE(NOME)
VALUES ('Cura')

INSERT INTO HABILIDADES(NOME,ID_TIPO_HABILIDADE)
VALUES ('Lança Mortal', '1'),('Escudo Supremo', '2'),('Recuperar vida', '4')

INSERT INTO CLASSES(NOME)
VALUES ('Bárbaro'),('Cruzado'),('Caçadora'),('Monge'),('Necromante'),('Feiticeiro'),('Arcanista')

INSERT INTO PERSONAGENS(NOME, CAPACIDADE_MAXIMA_VIDA, CAPACIDADE_MAXIMA_MANA, DATA_DE_ATUALIZACAO, DATA_DE_CRIACAO, ID_CLASSE)
VALUES ('DeuBug', '100', '80', GETDATE(), '18/01/2019', 1),('BitBug', '70', '100', GETDATE(), '17/03/2019', 4),('Fer8', '75', '60', GETDATE(), '18/03/2019', 7)

INSERT INTO CLASSE_HABILIDADE(ID_CLASSE, ID_HABILIDADE)
VALUES (1, 1), (1, 2), (2, 2), (3, 1), (4, 3), (4, 2), (6, 3)