UPDATE PERSONAGENS SET NOME = 'Fer7' WHERE ID = 3

UPDATE CLASSES SET NOME = 'Necromancer' WHERE ID = 5

SELECT * FROM PERSONAGENS

SELECT * FROM CLASSES

SELECT CLASSES.NOME FROM CLASSES

SELECT * FROM HABILIDADES

SELECT COUNT(*) FROM HABILIDADES

SELECT HABILIDADES.ID FROM HABILIDADES ORDER BY ID

SELECT * FROM TIPO_HABILIDADE

SELECT HABILIDADES.*, TIPO_HABILIDADE.NOME
